application_name: Rust OPC UA Server
application_uri: urn:RustOPCUA:Server
product_uri: urn:RustOPCUA:Product
create_sample_keypair: true
pki_dir: ./pki
trust_client_certs: true
auto_accept_trusted_certs: true

tcp_config:
  hello_timeout: 30
  session_timeout: 300000
  host: 0.0.0.0
  port: 4840

limits:
  max_sessions: 100
  max_message_size: 16777216
  max_chunk_count: 1000
  send_buffer_size: 16777216
  receive_buffer_size: 16777216
  subscriptions:
    max_subscriptions_per_session: 100
    max_monitored_items_per_sub: 100000
    max_monitored_item_queue_size: 100
  operational:
    max_monitored_items_per_call: 100000

locale_ids:
  - en

user_tokens:
  anonymous:
    user: anonymous
    pass: ""

discovery_urls:
  - opc.tcp://127.0.0.1:4840

endpoints:
  none:
    path: /
    security_policy: None
    security_mode: None
    security_level: 0
    user_token_ids:
      - ANONYMOUS
